### ISSUE TITLE
Missing error message when creating recipe fails

### ISSUE THREAD

**Issue by dentych** [dentych/dinner-dash#35]
When creating a new recipe with returns, which causes an error message from the server, the website will go to the recipes page, which is missing the recipe that one would have thought would be present.

Reproduction:

1. Go to recipe creation page
2. Input name only in name part of recipe
3. Click submit button
4. Website goes to recipe page and recipe is missing
  Should be possible to see the HTTP call as failed in dev tools.

**Comment by benlarsendk** [comment]
Can't reproduce? I see the recipe after submitting with only name,

**Comment by dentych** [comment]
I already fix
